name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  avatar_glow: 2.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  google_sign_in: ^5.3.0
  introduction_screen: 3.0.2
  lottie: ^1.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logo/
    - assets/lottie/
  uses-material-design: true
